# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    # We do not need any port mappings because we are using network mode "host"
    ports:
       - "8081:8081"
       - "__NAS_IP__:53:53/tcp"
       - "__NAS_IP__:53:53/udp"
       - "__NAS_IP__:67:67/udp"   # Only required if you are using Pi-hole as your DHCP server
       - "__NAS_IP__:123:123/udp" # Only required if you are using Pi-hole as your DHCP server
    environment:
      DNSMASQ_LISTENING: local
      DNSMASQ_USER: root
      TZ: 'Europe/Berlin'
      FTLCONF_webserver_port: 8081
      FTLCONF_webserver_api_password: '__WEB_UI_PASSWORT__' # Change this when creating the container
    # Volumes store your data between container upgrades
    volumes:
    #  - '/volume1/docker/pihole/var:/var'
      - '/volume1/docker/pihole/etc:/etc/pihole'
      - '/volume1/docker/pihole/dnsmasq:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
    #network_mode: host